sudo: true

language: php
php:
 - 7.0

before_script:
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.3
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - chmod +x ./ci/travis.sh
 - chmod +x ./ci/lint.sh
 - composer install

script:
 - ./ci/travis.sh

notifications:
  email: false

before_deploy:
 - mv plugins/Turanic/Turanic*.phar plugins/Turanic/Turanic.phar
